### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by panterz** [bauschan/generator-jquery-mobile#4]
After I run: 
yo jquery-mobile

I am getting this error:

> grunt-lodashbuilder@0.1.7 postinstall /home/pterzis/Documents/projects/cobweb/app2/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder
> node ./bin/post-install.js

module.js:340
    throw err;
          ^
Error: Cannot find module '../node_modules/lodash/vendor/tar/tar.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/pterzis/Documents/projects/cobweb/app2/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder/bin/post-install.js:14:13
    at Object.<anonymous> (/home/pterzis/Documents/projects/cobweb/app2/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder/bin/post-install.js:166:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by puzzithinker** [comment]
same here

**Comment by zeroxme** [comment]
same here!

**Comment by crazedVic** [comment]
If you navigate to where you installed the generator-jquery-mobile:

npm\node_modules\generator-jquery-mobile\app\templates

and open the file _package.json

https://github.com/bauschan/generator-jquery-mobile/blob/master/app/templates/_package.json

and change line 22 to:

```
"grunt-contrib-requirejs": "~0.4.1",
```

it works.  i'm totally new to github and have no idea how to get them to just fix the file.  perhaps someone else can take it on.

V

**Comment by bauschan** [comment]
Fixed in latest.
