### ISSUE TITLE
var isBinaryFile = require('isbinaryfile').isBinaryFileSync;

### ISSUE THREAD

**Issue by stefek99** [bauschan/generator-jquery-mobile#6]
You need to remove **isBinaryFileSync** in order to work.

Then: 

```
> grunt-lodashbuilder@0.1.7 postinstall /Users/michalstefanow/Dropbox/WWW Code/node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder
> node ./bin/post-install.js


module.js:340
    throw err;
          ^
Error: Cannot find module '../node_modules/lodash/vendor/tar/tar.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /node_modules/grunt-requirejs/node_modules/grunt-lodashbuilder/bin/post-install.js:14:13
    at Object.<anonymous> (/node_modules/grunt-lodashbuilder/bin/post-install.js:166:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

Generally - is anyone using this generator?

**Comment by bauschan** [comment]
Fixed in latest.
